# Base image
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app /app
COPY . .
EXPOSE 3000
CMD ["npm", "start"

